name: Update Examples List in README

on:
  pull_request:
    branches:
      - main
    paths:
      - "examples/**"
      - "techs.json"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Update README
        run: bun run scripts/update-readme.ts

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md with updated examples and technologies" || echo "No changes to commit"

      - name: Push changes
        run: git push origin ${{ github.head_ref }}
